### ISSUE TITLE
Update component

### ISSUE THREAD

**Issue by luisfuertes** [joelrfcosta/react-native-logentries#1]
Can you update component for run with last versions of RN?

**Comment by joelrfcosta** [comment]
@luisfuertes it should work with current RN version. Did you had any issue? (Just a reminder: it does not work on Android yet)

**Comment by alanmac** [comment]
Hi any update on Android support?

**Comment by joelrfcosta** [comment]
Hey @alanmac, sorry no news about Android yet, but you are free to submit a PR if you have time ;)

**Comment by Jarred-Sumner** [comment]
To get this working with React Native 0.42, I have to modify `RCTLogentries.h`:

From:

```objectivec
#import "RCTBridgeModule.h"

@interface RCTLogentries : NSObject <RCTBridgeModule>

@end

```

To:
```objectivec
#import <React/RCTBridgeModule.h>

@interface RCTLogentries : NSObject <RCTBridgeModule>

@end

```

It'd be great if you could do this in the package itself, so I don't have to make changes manually whenever I run `yarn install`.

**Comment by Jarred-Sumner** [comment]
Oh wait! It looks like you've actually already done this. Can you publish an updated NPM package? :)

**Comment by joelrfcosta** [comment]
Sure thing @Jarred-Sumner! Published a new version to npm (now with Android support ;) )
