### ISSUE TITLE
Getting error when running the app with react-native run-android

### ISSUE THREAD

**Issue by jigarmistry** [joelrfcosta/react-native-logentries#4]
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-logentries'.
   > Could not resolve all dependencies for configuration ':react-native-logentries:_debugCompile'.
      > Could not resolve com.github.LogentriesCommunity:le_android:logentries-android-4.4.1.
        Required by:
            daphnencc:react-native-logentries:unspecified
         > Could not resolve com.github.LogentriesCommunity:le_android:logentries-android-4.4.1.
            > Could not get resource 'https://jitpack.io/com/github/LogentriesCommunity/le_android/logentries-android-4.4.1/le_android-logentries-android-4.4.1.pom'.
               > Could not GET 'https://jitpack.io/com/github/LogentriesCommunity/le_android/logentries-android-4.4.1/le_android-logentries-android-4.4.1.pom'.
                  > peer not authenticated

Can anybody tell me how can I solve this ?

**Comment by joelrfcosta** [comment]
Hey @jigarmistry, were you able to fix this?

**Comment by joelrfcosta** [comment]
I suppose it is fixed already ;) Let me know if this happen again.
