### ISSUE TITLE
is there a way to set deviceId ?

### ISSUE THREAD

**Issue by ngrj** [joelrfcosta/react-native-logentries#6]
Hi, first of all thanks for your awesome module. I've just set up log entries for first time, I was wondering if there is a way I can set deviceId for logs coming from particular devices. Also is it possible to enhance module to also have log levels like warn, error ?
If yes, I can try to implement and send a PR

**Comment by joelrfcosta** [comment]
@ngrj what do you mean with set deviceId? If you construct the log message with a specific structure you will be able to filter per deviceId using Logentries LEQL

> With our intuitive query language, LEQL, you can use analytical functions such as AVERAGE(), COUNT(), GROUPBY(), min, max and percentile.

You can find more info about search here: https://docs.logentries.com/docs/setup-search-logs
